# Generated by Django 4.2.5 on 2024-02-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_center', models.CharField(max_length=255)),
                ('number_contract', models.CharField(default=None, max_length=255)),
                ('start_contract', models.DateField()),
                ('data_to', models.DateField()),
                ('data_contract', models.DateField()),
                ('landlord', models.CharField(max_length=255)),
                ('tenant', models.CharField(max_length=255)),
                ('landlordPC', models.CharField(max_length=255)),
                ('type_contract', models.CharField(max_length=255)),
                ('advertising_tax', models.CharField(max_length=255)),
                ('working', models.CharField(max_length=255)),
                ('closed', models.CharField(max_length=255)),
                ('comment', models.CharField(default=None, max_length=255)),
                ('number_contract_count', models.CharField(default=None, max_length=255)),
                ('main_contract', models.CharField(max_length=255)),
                ('main_lot', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
