# Generated by Django 4.2.5 on 2024-02-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_new_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='advertising_tax',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='closed',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='working',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
