# Generated by Django 4.2.5 on 2024-02-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_new_tenant', '0002_alter_client_advertising_tax_alter_client_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='landlordPC',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
