# Generated by Django 4.2.5 on 2024-02-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_new_tenant', '0003_alter_client_landlordpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='main_contract',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='main_lot',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_contract_count',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_contract',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
